### ISSUE TITLE
BUG - Emails continue to flock in SPAM folder. Tried a new import

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#704]
![image](https://user-images.githubusercontent.com/55691499/82220416-35ec7d80-993c-11ea-97fd-d9cadce14193.png)

Also there is no " Connect to QB " Link

![image](https://user-images.githubusercontent.com/55691499/82220525-60d6d180-993c-11ea-8fc2-cb2de7781bc8.png)

**Comment by robiulpro** [comment]
Nothing to do with the code. I've done few changes in aws settings. If still not resolved we have to wait till we move to production.

**Comment by robiulpro** [comment]
This is fixed, please verify.

**Comment by HazelColaco19** [comment]
It does come in main account now, both the emails.


![image](https://user-images.githubusercontent.com/55691499/82316298-39d6d900-99ea-11ea-8c65-baf87b0f4966.png)



However I do get the security pop up. Is it because of the sub domain being used? If yes, then let me know so that I can close the ticket. @robiulpro

**Comment by robiulpro** [comment]
You have received the above mail at 11.17 as per image, could you please check the latest email and see if its already exists.

**Comment by HazelColaco19** [comment]
I still get this @robiulpro 

![image](https://user-images.githubusercontent.com/55691499/82320014-2c245200-99f0-11ea-8aa9-39d98af3196c.png)

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/82321582-afdf3e00-99f2-11ea-8104-a5534516f070.png)
